### ISSUE TITLE
Цвет кнопки Back

### ISSUE THREAD

**Issue by Nejern** [ZLP-LLC/Jokes-Frontend#3]
Кнопка имеет очень схожий с фоном цвет.
![Screenshot_2024-05-22-22-19-13-50_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/ZLP-LLC/Jokes-Frontend/assets/62671417/0a0424a5-acc1-47d1-98d6-ab472dc2f2ae)

**Comment by Rulemore** [comment]
Отъебись

**Comment by nonemoff** [comment]
иди переделывай **выблядок** сука падла сдохни

**Comment by Rulemore** [comment]
Я просто удалю кнопку

**Comment by Nejern** [comment]
Жду PR
